export const SET_LOADING = "SET_LOADING"
export const GET_MESSAGE = "GET_MESSAGE"
export const GET_MESSAGE_REQUESTED = "GET_MESSAGE_REQUESTED"
export const CREATE_MESSAGE = "CREATE_MESSAGE"
export const CREATE_MESSAGE_REQUESTED = "CREATE_MESSAGE_REQUESTED"
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';