## create user

POST http://localhost:5000/v1/signUp
content-type: application/json

{
  "name": "JohnDoe",
  "email": "cafive3s132@talmetry.com",
  "password": "password123",
  "age": 25,
  "verified": true,
  "isActive": true
}


########## Get users 
GET http://localhost:5000/v1/users
content-type: application/json


######### ADD message
POST http://localhost:5000/v1/messages
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY1YTAzOGZmYWZiYWRjNDhmYTY1M2Y1NiIsIm5hbWUiOiJKb2huRG9lIiwiZW1haWwiOiJjYWZpdmUzczEzMkB0YWxtZXRyeS5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRSWldqS3hBdFlMRXNUbWxTS0ZuTmdPdmpNSE9RMXV6dGU0SHQ1T0tjSjNDaU9tOEdTSThoSyIsImFnZSI6MjUsInZlcmlmaWVkIjpmYWxzZSwiaXNBY3RpdmUiOnRydWUsInJvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyNC0wMS0xMVQxODo1Mjo0Ny4zMDBaIiwidXBkYXRlZEF0IjoiMjAyNC0wMS0xMVQxODo1Mjo0Ny4zMDBaIiwiX192IjowfSwiaWF0IjoxNzA1MDAxMDMxLCJleHAiOjE3MDUwMDQ2MzF9.HzArRZYZ_SWT5LoBF6cplEG61is766jyauDQ7sRDdGY

{
  "message": "Hello World",
  "receviedId": "5f9b3b3b9b9b9b9b9b9b9b9b"
  

}


#### login
POST http://localhost:5000/v1/signin
content-type: application/json

{
 "email": "cafive3s132@talmetry.com",
  "password": "password123"
}

#### get messages
GET http://localhost:5000/v1/messages
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY1YTJiZTI2Njc1MjI3MzczZjA2OThmZSIsIm5hbWUiOiJKb2huRG9lIiwiZW1haWwiOiJjYWZpdmUzczEzMkB0YWxtZXRyeS5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRWRENNbEVPbXBwL09tMXlHSlB4MDQuaUM0b1NQODJFQVB4Sng2MFFkUHJYYUtpYTFIWVBVeSIsImFnZSI6MjUsInByb2ZpbGVQaG90byI6eyJ1cmwiOiJodHRwczovL21lZGlhLmlzdG9ja3Bob3RvLmNvbS9pZC8xMzAwODQ1NjIwL3ZlY3Rvci91c2VyLWljb24tZmxhdC1pc29sYXRlZC1vbi13aGl0ZS1iYWNrZ3JvdW5kLXVzZXItc3ltYm9sLXZlY3Rvci1pbGx1c3RyYXRpb24uanBnP3M9MjA0OHgyMDQ4Jnc9aXMmaz0yMCZjPTZoUU5BQ1FRamt0bmk4Q3hTU19RU1BxSnYydHljc2tZbXBGR3p4djNGTnM9IiwicHVibGljSWQiOm51bGx9LCJ2ZXJpZmllZCI6ZmFsc2UsImlzQWN0aXZlIjp0cnVlLCJyb2xlIjoidXNlciIsImNyZWF0ZWRBdCI6IjIwMjQtMDEtMTNUMTY6NDU6MjYuMTQyWiIsInVwZGF0ZWRBdCI6IjIwMjQtMDEtMTNUMTY6NDU6MjYuMTQyWiIsIl9fdiI6MH0sImlhdCI6MTcwNTE3MzA0NiwiZXhwIjoxNzA1MTc2NjQ2fQ.YYYQx9Beq9hec-tp-F56vEW5xV5S5mc20wz-WEoESQk
#### update user
PATCH http://localhost:5000/v1/user/659d525f0fe31c066c396476
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY1OWQ1MjVmMGZlMzFjMDY2YzM5NjQ3NiIsIm5hbWUiOiJKb2huRG9lIiwiZW1haWwiOiJjYWZpdmUzMTMyQHRhbG1ldHJ5LmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJDFsZi94VVlnb2d1N0Y4M1dMZjhiUmV4VjFqenJrdHVwczd0U1o1MmRhcUZDaXU1cFdOQ0hXIiwiYWdlIjoyNSwidmVyaWZpZWQiOmZhbHNlLCJpc0FjdGl2ZSI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyNC0wMS0wOVQxNDowNDoxNS4zNzNaIiwidXBkYXRlZEF0IjoiMjAyNC0wMS0wOVQxNDowNDoxNS4zNzNaIiwiX192IjowfSwiaWF0IjoxNzA0ODE2NTQ2LCJleHAiOjE3MDQ4MjAxNDZ9.nv98JGZ30WJVQkZxOVISf_2wV07NZJHSV2c_J1hJKao

{
  "name": "JohnDoe",
  "email": ""
}


#### Update message
PATCH http://localhost:5000/v1/messages/65a042969044b6d9ad4e7807
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY1YTAzOGZmYWZiYWRjNDhmYTY1M2Y1NiIsIm5hbWUiOiJKb2huRG9lIiwiZW1haWwiOiJjYWZpdmUzczEzMkB0YWxtZXRyeS5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRSWldqS3hBdFlMRXNUbWxTS0ZuTmdPdmpNSE9RMXV6dGU0SHQ1T0tjSjNDaU9tOEdTSThoSyIsImFnZSI6MjUsInZlcmlmaWVkIjpmYWxzZSwiaXNBY3RpdmUiOnRydWUsInJvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyNC0wMS0xMVQxODo1Mjo0Ny4zMDBaIiwidXBkYXRlZEF0IjoiMjAyNC0wMS0xMVQxODo1Mjo0Ny4zMDBaIiwiX192IjowfSwiaWF0IjoxNzA1MDAxMDMxLCJleHAiOjE3MDUwMDQ2MzF9.HzArRZYZ_SWT5LoBF6cplEG61is766jyauDQ7sRDdGY

{
  "message": "Hello Worlsssd"
}

#### Post Photo

POST http://localhost:5000/v1/profile
Content-Disposition: form-data; name="image"; filename="1.png"
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY1YTAzOGZmYWZiYWRjNDhmYTY1M2Y1NiIsIm5hbWUiOiJKb2huRG9lIiwiZW1haWwiOiJjYWZpdmUzczEzMkB0YWxtZXRyeS5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRSWldqS3hBdFlMRXNUbWxTS0ZuTmdPdmpNSE9RMXV6dGU0SHQ1T0tjSjNDaU9tOEdTSThoSyIsImFnZSI6MjUsInZlcmlmaWVkIjpmYWxzZSwiaXNBY3RpdmUiOnRydWUsInJvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyNC0wMS0xMVQxODo1Mjo0Ny4zMDBaIiwidXBkYXRlZEF0IjoiMjAyNC0wMS0xMVQxODo1Mjo0Ny4zMDBaIiwiX192IjowfSwiaWF0IjoxNzA1MDAxMDMxLCJleHAiOjE3MDUwMDQ2MzF9.HzArRZYZ_SWT5LoBF6cplEG61is766jyauDQ7sRDdGY
Content-Type: image/png

< ./1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW-->

